### ISSUE TITLE
Support importing library files that set a global

### ISSUE THREAD

**Issue by zepumph** [phetsims/chipper#1409]
Over in https://github.com/phetsims/phet-io-wrappers/issues/555#issuecomment-1747324375, @samreid and @jbphet and I are interested in using a dependency file to achieve a goal. The default way to accomplish this is to add it as a preload, regenerate every single dev HTML, and add support for it in PhET-iO code separately if needed. I'd like to change that!

We saw that for libraries that support UMD with a global and also a `module.exports`, we can use `expose-loader` to make this work. https://webpack.js.org/loaders/expose-loader/.

We have a working prototype, but before committing, I would like to try it out in a couple of other spots to make sure that it is feasible in its current form (in `webpackBuild`)

**Comment by samreid** [comment]
Will we be able to import SimVersion with this?

**Comment by pixelzoom** [comment]
https://github.com/phetsims/phet-io-wrappers/commit/faaf4b3c76e2372d18d3b4c0e6390c4848ed77b6 left me dead in the water.  Attempting to run Studio with any sim resulted in:

> studio-main.ts:40 Uncaught TypeError: phetio.Client is not a constructor
    at studio-main.ts:40:22

So I reverted that commit. @zepumph FYI.

**Comment by zepumph** [comment]
The change requires a restart to the transpiler which I didn't think through before commit. That should solve the problem, but otherwise I will be on zoom if you'd like to pair on any trouble you encounter.

**Comment by zepumph** [comment]
We got to a commit point today for PeggyJS, and it is working well. I would like to try to make one more file support this while it is still fresh in my mind.

**Comment by zepumph** [comment]
I think Himalaya will be pretty plug and play from initial inspection. I wonder though if we have to worry about licensing concerns. @samreid do you think it matters if we import or preload our code?

**Comment by zepumph** [comment]
Over in https://github.com/phetsims/scenery/issues/1583, converting himalaya to an import was plug and play. I'm so happy and excited for what this means!!!

Still TODO:
- [ ] We need a better system for defining the files. The regex is untenable. 
- [ ] It is annoying to have to remember that Transpiler needs a line like this, perhaps we can import data used by webpack in transpiler for both. 
- [ ] What other files can we use for this? 
- [ ] I wonder if we should add the gameup harness to this conversation, which already get's imported, but it doesn't need a global. Should we expand the possible usages of this feature?

**Comment by samreid** [comment]
>  I wonder though if we have to worry about licensing concerns. @samreid do you think it matters if we import or preload our code?

I see that `reportThirdParty.js` loads from https://github.com/phetsims/sherpa/blob/main/lib/license.json, so I think as long as an `import`ed library is listed in that json, it will still appear correctly in the license report.

**Comment by zepumph** [comment]
I think I was most worried about something like:

```
// Copyright 2023, University of Colorado Boulder

import '../sherpa/lib/himalaya';
```

But that is the exact same way we have things set up for lodash or jquery or grunt, so I don't know why I was worried. Thanks!

**Comment by zepumph** [comment]
I'm ready to have a quick chat about what more to do here with @samreid. It shouldn't need to be too long. Perhaps we can talk about SimVersion.

**Comment by zepumph** [comment]
SimVersion will be handled in https://github.com/phetsims/perennial/issues/336. And other worries about the phet-io side of things (like loading package.json) will be handled in https://github.com/phetsims/phet-io-wrappers/issues/597.

@samreid I think this is ready to close. You?

**Comment by samreid** [comment]
Sounds good, thanks. Closing.
