### ISSUE TITLE
duplicated code in media plugins

### ISSUE THREAD

**Issue by samreid** [phetsims/chipper#229]
From #221

**Comment by samreid** [comment]
image and mipmap are very similar, but audio is a bit different because it uses a suffix-less name to load files with two suffixes.  @pixelzoom can you review this duplicated code and suggest a way to factor it out, or if you recommend to leave it as is?

Here is the copied code:
**image.js**
```js
        var licenseEntry = getLicenseEntry( path );

        // Check for errors, but only if the brand is 'phet', see #176
        if ( (phet.chipper.brand === 'phet' || phet.chipper.brand === 'phet-io') && LicenseEntryClassifier.isProblematic( licenseEntry ) ) {
          onload.error( new Error( 'problematic license entry' ) );
        }
        else {
          global.phet.chipper.licenseEntries.images = global.phet.chipper.licenseEntries.images || {};
          global.phet.chipper.licenseEntries.images[ name ] = licenseEntry;
          onload( null );
        }
```

**mipmap.js**
```js
        var licenseEntry = getLicenseEntry( path );

        // Check for errors, but only if the brand is 'phet', see #176
        if ( (phet.chipper.brand === 'phet' || phet.chipper.brand === 'phet-io') && LicenseEntryClassifier.isProblematic( licenseEntry ) ) {
          onload.error( new Error( 'problematic license entry' ) );
        }
        else {
          global.phet.chipper.licenseEntries.images = global.phet.chipper.licenseEntries.images || {};
          global.phet.chipper.licenseEntries.images[ name ] = licenseEntry;
          onload( null );
        }
```

**audio.js**
```js
        var errorString = '';
        for ( var i = 0; i < urlList.length; i++ ) {
          var licenseEntry = getLicenseEntry( urlList[ i ].url );

          // Check for errors, but only if the brand is 'phet', see #176
          if ( (phet.chipper.brand === 'phet' || phet.chipper.brand === 'phet-io') && LicenseEntryClassifier.isProblematic( licenseEntry ) ) {
            errorString += 'Error for ' + urlList[ i ].url;
          }
          else {
            global.phet.chipper.licenseEntries.audio = global.phet.chipper.licenseEntries.audio || {};
            global.phet.chipper.licenseEntries.audio[ name ] = licenseEntry;
          }
        }
        if ( errorString !== '' ) {
          onload.error( new Error( errorString ) );
        }
        else {
          onload( null );
        }
```

**Comment by pixelzoom** [comment]
This bit was encapsulated isAcceptableLicenseEntry by https://github.com/phetsims/chipper/issues/240:

`if ( (phet.chipper.brand === 'phet' || phet.chipper.brand === 'phet-io') && LicenseEntryClassifier.isProblematic( licenseEntry ) ) `

**Comment by pixelzoom** [comment]
@samreid The code is indeed identical for image.js and mipmap.js.  Is there any reason why it needs to differ for audio.js?  Ie, why does audio.js need to build up and error string instead of using the error-per-file approach in the other plugins?

**Comment by samreid** [comment]
Audio plugins typically use the "suffix-less" version, and it automatically finds all of the exact files with the appropriate suffixes.

**Comment by pixelzoom** [comment]
Hmmm... So what goes in audio/license.json? Is the entry suffix-less, to denote a collection of files? Or is there a license entry for each file?

**Comment by pixelzoom** [comment]
Answered my own question by looking at john-travoltage/audio/license.json.  There is an entry per media file. That seems redundant. But if we're going to do with that, what is the advantage of concatenation error message, rather than having 1 error message per audio file?

**Comment by pixelzoom** [comment]
> what is the advantage of concatenating error messages, rather than having 1 error message per audio file?

And if there are advantages, are they worth the difficulties involved in trying to factor out duplicate code from this section of audio.js, see https://github.com/phetsims/chipper/issues/229.

**Comment by samreid** [comment]
Some of the audio files only have one recording, such as empty.mp3, which is part of the complication.

Concatenating the error messages was just a simple way of identifying if *any* of the files had problematic licensing, and reporting the names for all problematic files.

I've factored out the duplicated logic code across the 3 plugins with a require module and an adapter.  Tested with grunt for forces-and-motion-basics, building with the usual case, and building with --brand=phet and a synthetic error in the audio license.json.  Nothing amiss.  @pixelzoom can you please review this solution and let me know if you have questions or recommendations?  After I commit, of course.

**Comment by samreid** [comment]
Commit is above.  In my test, I also confirmed that the output in the HTML file for 3rd parties looked correct.

**Comment by samreid** [comment]
I'm sensing an issue when running the requirejs version of a sim (non-built).  Back to me for investigation.

**Comment by samreid** [comment]
Correction: requirejs mode runs ok, the built version is having this problem:
"../../chipper/js/grunt/checkAndRegisterLicenseEntry missing ../../chipper/js/grunt/../../../chipper/js/grunt/getLicenseEntry"

**Comment by samreid** [comment]
It seems like requirejs is having trouble requiring files from a file required from a plugin.  I have no idea why.  For now I'll commit a workaround that loads all of the require statements in each plugin, then passes them through to the shared code.  @jonathanolson & I identified this as a working solution and I tested by building and launching forces and motion basics.

**Comment by samreid** [comment]
Fixed above.  Not really sure how to make progress on this since I don't know why requirejs is having trouble loading these require statements.  Perhaps I'll post the build error here tomorrow and we can go from there.

**Comment by samreid** [comment]
OK, starting with the code above which loads all plugin dependencies from the plugin itself I made the following changes:

1. change IIFE in checkAndRegisterLicenseEntry.js to a define declaration
2. use require statements in checkAndRegisterLicenseEntry.js

Build completes successfully.  Then running, I see this issue:

```
Uncaught Error: ../../chipper/js/requirejs-plugins/checkAndRegisterLicenseEntry missing ../../chipper/js/requirejs-plugins/../../../chipper/js/grunt/getLicenseEntry
```

**Comment by samreid** [comment]
Well, if I load the dependencies in audio, image and mipmap I can still define checkAndRegisterLicense entry in a define block, so I committed that above.  Build and launching build work properly.

**Comment by samreid** [comment]
Not sure where to go next, can I get some help from @pixelzoom or @jonathanolson?

**Comment by samreid** [comment]
Tagged as developer-meeting so I can make others aware of this issue and ask for help.

**Comment by samreid** [comment]
@pixelzoom said he wanted to look into this.

**Comment by pixelzoom** [comment]
@samreid I still don't see the value in concatenating the error messages for a group of related audio files. The end result is the same - or should be the same; it's currently not because the error messages are concatenated without any separator.  And it results in this ugly bit of adapter code in audio.js:

```js
        var errors = [];
        var onLoadAdapter = function() { };
        onLoadAdapter.error = function( error ) {
          errors.push( error );
        };
        for ( var i = 0; i < urlList.length; i++ ) {
          checkAndRegisterLicenseEntry( name, urlList[ i ].url, global.phet.chipper.brand, 'audio', onLoadAdapter, getLicenseEntry, isAcceptableLicenseEntry );
        }

        // If any license entry was a problem, then we must fail the build, for simplicity, just report the first error
        if ( errors.length > 0 ) {
          onload.error( errors[ 0 ] );
        }
        else {
          onload( null );
        }
``` 

Any reason why we can't just do this in audio.js?:

```js
checkAndRegisterLicenseEntry( name, urlList[ i ].url, global.phet.chipper.brand, 'audio', onload, getLicenseEntry, isAcceptableLicenseEntry );
```

**Comment by pixelzoom** [comment]
Discussed with @samreid via phone.  The adapter is needed because we only want to call onload(null) once per invocation of a plugin.

**Comment by pixelzoom** [comment]
In checkAndRegisterLicenseEntry, `require` has this value during build and in requirejs mode:

```
function localRequire(deps, callback, errback) {
  // .... several dozen lines of code
}
```

and this value when the built html file is run:

`function (){return u.apply(t,b.call(arguments,0).concat([e,i]))}`

**Comment by pixelzoom** [comment]
Hmmm... If I inspect the value of `require` in audio.js in the above cases, it's the same as in checkAndRegisterLicenseEntry.js.  So I'm not sure why checkAndRegisterLicenseEntry.js is having a problem and audio.js isn't.

**Comment by pixelzoom** [comment]
Scratch that... I wasn't inspecting audio.js, Chrome was apparently caching.

**Comment by pixelzoom** [comment]
Curious that, at build time, I can't get any console.log output from the media plugins. They are run by the `requirejs:build` task.  Does that task suppress logging, or direct it somewhere else?

**Comment by pixelzoom** [comment]
Skype:

[8/11/15, 2:37:08 PM] Jonathan Olson: the plugins don't run in built versions, they run while building
[8/11/15, 2:37:51 PM] Jonathan Olson: they do output a small string that will be included that WILL be executed for the module though

**Comment by pixelzoom** [comment]
I went round and round on this, then tried doing what @samreid reported didn't work in https://github.com/phetsims/chipper/issues/229#issuecomment-129703907.  I don't see that problem - it works fine in requirejs mode, during the build, and in the built html file.    I'm testing with john-travoltage, which has audio, images and mipmaps (from joist).

**Comment by pixelzoom** [comment]
I renamed checkAndRegisterLicenseEntry.js to registerLicenseEntry.js, and absorbed isAcceptableLicenseEntry.js into it as private functions.

**Comment by pixelzoom** [comment]
Summary:  
• checkAndRegisterLicenseEntry.js was renamed to registerLicenseEntry.js
• isAcceptableLicenseEntry.js was absorbed into registerLicenseEntry.js
• Prior to the above changes, I couldn't reproduce the problem that @samreid was having. And it was ultimately moot, since the above changes eliminated the need for `require` statements in registerLicenseEntry.js 
• tested with john-travoltage and ohms-law, which have audio, images and mipmaps (from joist)

Back to @samreid for verification.

**Comment by samreid** [comment]
Did you have a hypothesis why the node and require definitions were necessary when using the 2-file approach (though agreed it is currently moot)?

**Comment by samreid** [comment]
I built john-travoltage and inspected the HTML and didn't see any issues.  I looked at the change sets above and it seems good.

The only thing that is tricky in this file for me is I have trouble grokking:
```js
var acceptable = !isApplicableBrand( brand ) || isCompatibleLicenseEntry( entry ) || !!entry.exception;
```

I tried a few rewritings and couldn't come up with something much better.  Perhaps it would be nice if @pixelzoom could write a line comment explaining a good way to think of this line--in this case I understand what the line is doing but don't have a good intuitive understanding of how it does it.  Expanding it to a few `if` statements didn't seem great.

Reassigning to @pixelzoom to discuss the issues in this comment and the comment above.

**Comment by pixelzoom** [comment]
I'm not sure how to make this any clearer. Does the function doc not clarify the definition of "acceptable"?

> * Determines whether a license entry is "acceptable". For PhET brands, a license entry is acceptable
   * if it is compatible with PhET licensing policies, or if it has an "exception" field explaining why
   * PhET licensing policies can be ignored. For non-PhET brands, all license entries are acceptable.

**Comment by pixelzoom** [comment]
> Did you have a hypothesis why the node and require definitions were necessary when using the 2-file approach (though agreed it is currently moot)?

I did not add the node and require definitions. I used your original solution without change and it worked fine.

**Comment by samreid** [comment]
Hmmm..  I wonder what the problem was.

I know what this line is supposed to do and the documentation is clear.
```js
var acceptable = !isApplicableBrand( brand ) || isCompatibleLicenseEntry( entry ) || !!entry.exception;
```

But the implementation is difficult for me to read.  I'll have a go at telling you how my brain parses it:

> if the brand is not applicable or the license entry is compatible or the entry has an exception, then the entry is acceptable.

Perhaps the issue is the naming of the method isApplicableBrand--maybe if this was called `brandRequiresLicenseChecks`??

**Comment by pixelzoom** [comment]
@samreid Does the above change make things clearer?

**Comment by samreid** [comment]
That's nicer, thanks.  And it leads to a good place to document the logic. I'll take another look through and close if everything looks good.

**Comment by samreid** [comment]
All changes in registerLicenseEntry.js look good.  @pixelzoom anything else to do here?

**Comment by pixelzoom** [comment]
@samreid This is a nit, but we agreed to standardize on {Object}, not {object} as you've added in https://github.com/phetsims/chipper/commit/78ff458d354656b101af635698a5a625d511de3f

I also don't get the purpose of the blank lines in isCompatibleLicenseEntry, but I'll roll with it. Are you suggesting that every comment should be preceded by a blank line?

**Comment by pixelzoom** [comment]
From the example in the PhET Development Overview:

```
 * @param {string} name - full name
 * @param {number} age - age, in years
 * @param {boolean} isEmployee - whether this developer is an employee of CU
 * @param {function} callback - called immediate after coffee is consumed
 * @param {Property.<number>} hoursProperty - cumulative hours worked
 * @param {string[]} friendNames - names of friends
 * @param {Object} [options] - optional configuration, see constructor
```

**Comment by samreid** [comment]
@pixelzoom said:

> I also don't get the purpose of the blank lines added to isCompatibleLicenseEntry in cc8a94c,

From the Style Guide:

> Line comments should be preceded by a blank line. 

Thanks for catching my casing error with Object, I'll fix it shortly.

**Comment by samreid** [comment]
I see 43 occurrences of `@param {object}` across our repos.  I'll hit all of them once my working copy is clean after work in #248

**Comment by pixelzoom** [comment]
> From the Style Guide:
> > Line comments should be preceded by a blank line.

In this case, I think that's misguided and unnecessary (especially for the else clause).

I'd like to hear from other developers on this one, Which of the following do you prefer?

Version (1):
```js
  function isCompatibleLicenseEntry( entry, brand ) {
    if ( brand === 'phet' || brand === 'phet-io' ) {

      // PhET-specific brands have these licensing policies
      return entry.projectURL === 'http://phet.colorado.edu' ||
             entry.license === 'Public Domain' ||
             entry.license === 'NASA';
    }
    else {

      // non-PhET brands have no licensing policies, so all entries are compatible
      return true;
    }
  }
```

Version (2):

```js
  function isCompatibleLicenseEntry( entry, brand ) {
    if ( brand === 'phet' || brand === 'phet-io' ) {
      // PhET-specific brands have these licensing policies
      return entry.projectURL === 'http://phet.colorado.edu' ||
             entry.license === 'Public Domain' ||
             entry.license === 'NASA';
    }
    else {
      // non-PhET brands have no licensing policies, so all entries are compatible
      return true;
    }
  }
```

**Comment by samreid** [comment]
OK I've finished #248 and ready to do a big query replace from `@param {object}` to `@param {Object}`.  Brace yourself for several commits.

**Comment by samreid** [comment]
OK I pushed 43 fixes above for `@param {object}` => `@param {Object}`.  I didn't do any more sophisticated regex or string matching.  I think I'm done here, I'll unassign and we can discuss the above issues at the next developer meeting.

**Comment by pixelzoom** [comment]
8/13/15 dev meeting consensus:  Easiest to stick with the existing policy, precede every comment with a blank line. Feel free to correct violations where you see them.

**Comment by pixelzoom** [comment]
All work completed on this issue, so closing.
